name: privy_181125
description: "privy device code shift to flutter"
publish_to: 'Pratik'

version: 1.0.0+1

environment:
  sdk: ^3.10.0


flutter_icons:
  android: true
  ios: true
  image_path: "assets/img.png"


#dependencies:
#  firebase_core: ^3.7.0
#  cloud_firestore: ^5.4.0
#  firebase_auth: ^5.1.0
#  flutter:
#    sdk: flutter
#  cupertino_icons: ^1.0.8

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^4.2.1
  firebase_database: ^12.1.0
  shared_preferences: ^2.1.1
  flutter_svg: ^1.1.6 # optional if you use svg icons
  image_picker: ^1.0.7
  flutter_blue_plus: ^1.32.8
  flutter_launcher_icons: ^0.13.1



  flutter_bluetooth_serial:
    git:
      url: https://github.com/edufolly/flutter_bluetooth_serial.git
      ref: master
#  permission_handler: ^12.0.1
  flutter_reactive_ble: ^5.0.3
#  permission_handler: ^11.3.0
  permission_handler: ^11.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0



flutter:
  uses-material-design: true

  assets:
    - assets/images/

flutter_native_splash:
  android: true
  ios: true
  fullscreen: true

  # Background color
  color: "#0A1227"

  # FASTEST way: use small logo + small background
  image: assets/images/logo.png      # must be <150 KB
  background_image: assets/images/home.png   # must be <200 KB

  android_gravity: full
  ios_content_mode: scaleAspectFill
